#Aula01 - Python Fundamentos I 

#Abaixo são os códigos para preparar um café da manhã.


print('Passos Para um Café da Manha Perfeito ')
print('PREPARANDO O CAFÉ DA MANHÃ PERFEITO:\n 1 - ESTENDER TOALHA NA MESA;\n 2 - COLOCAR AS LOUÇAS;')
print(' 3 - COLOCAR OS FRIOS SOBRE AS LOUÇAS DE FRIOS;\n 4 - COLOCAR GARRAFA DE CAFÉ SOBRE A MESA;')
print(' 5 - COLOCAR GARRAFA LEITE SOBRE A MESA;\n 6 - COLOCAR GARRAFA DE SUCO SOBRE A MESA;\n 7 - COLOCAR CESTA DE PÃES SOBRE A MESA;')
print(' 8 - COLOCAR CESTA DE FRUTAS SOBRE A MESA;\n 9 - SE SENTAR AO REDOR DA MESA PARA TER A REFEIÇÃO;\n 10- ACIONAR SERVIÇO DE LIMPEZA;')
